# Workflow for downloading and saving ChEBI secondary2primary mappings
name: chebi

on:
  workflow_dispatch:
  ##TODO: add schedule for deployment (suggestion: once a month in occurence with release schedule from ChEBI)

permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  chebi:
    runs-on: ubuntu-latest
    
    steps:
      # step 1: checkout the repository
      - name: Download GitHub repo for bash script (tba)
        uses: actions/checkout@v3

      # step 2: run the bash script for ChEBI data Download
      - name: Download data
        run: |
          ##Download ChEBI SDF file
          wget https://ftp.ebi.ac.uk/pub/databases/chebi/archive/rel223/SDF/ChEBI_complete_3star.sdf.gz
          ##Unzip gz file:
          gunzip ChEBI_complete_3star.sdf.gz
          
          ##Check file size if available
          ls
          ##Print file size
          FILENAME=ChEBI_complete_3star.sdf
          FILESIZE=$(stat -c%s "$FILENAME")
          echo "Size of $FILENAME = $FILESIZE bytes."

          ##Create temp. folder to store the data in
          mkdir -p mapping_preprocessing/datasources/ChEBI/data
          ##Move the SDF file to the expected location
          mv ChEBI_complete_3star.sdf mapping_preprocessing/datasources/ChEBI/data
     # step 3: run the R script for ChEBI preprocessing (to be made into separate job)
      - name: Run R script to process SDF data
        run: |
          ##Check R version:
          R --version
          ##Install the readr package:
          #Rscript -e 'install.packages("readr")'
          ##Running the R script:
          #Rscript r/ChEBI_processing.R
          #echo "R preprocessing of ChEBI data is done"
     # step 4: run the Java .jar for ChEBI preprocessing (to be made into separate job)
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11' 
      - name: Run .jar to process SDF data
        run: |
          inputFile = "mapping_preprocessing/datasources/ChEBI/ChEBI_complete_3star.sdf"
          outputDir = "mapping_preprocessing/datasources/ChEBI/data"
          java -cp target/mapping_prerocessing-0.0.1-SNAPSHOT-jar-with-dependencies.jar org.sec2pri.chebi_sdf $inputFile $outputDir


