name: Update Docker image
on:
  workflow_dispatch:

jobs:
  trigger-docker-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Trigger docker release
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.pat_external_workflow }}
          repository: jmillanacosta/omicsFixID
          event-type: update-event
