name: Check and test HGNC updates

on:
  workflow_dispatch:
  pull_request: # tests whether it is working on PR
     paths:
     - '.github/workflows/hgnc.yml'
  schedule:
    - cron: "0 0 1,15 * *"  # Run the workflow on the 1st and 15th day of each month
permissions:
  contents: write
  pages: write
  id-token: write
  issues: write


jobs:
  check_new_data:
    runs-on: ubuntu-latest
    name: Check the date of the latest data
    outputs:
      COMPLETE_NEW: ${{ steps.check_download.outputs.COMPLETE_NEW }}
      WITHDRAWN_NEW: ${{ steps.check_download.outputs.WITHDRAWN_NEW }}
      DATE_NEW: ${{ steps.check_download.outputs.DATE_NEW }}
      DATE_OLD: ${{ steps.check_download.outputs.DATE_OLD }}
    steps:
      # step 1: check the release date for the latest HGNC files
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check for new hgnc files
        id: check_download
        run: |
          ##Extract the date from the hgnc config file 
          date_old=$(grep -E '^date=' datasources/hgnc/config | cut -d'=' -f2)
          echo 'Accessing the hgnc data'
          wget https://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/archive/quarterly/tsv/ -O hgnc_index.html
          # Extracting the latest complete file
          complete=$(grep 'hgnc_complete_set' hgnc_index.html | awk -F '">|</a' '{print $2}' | head -n 1)
          # Extracting the latest withdrawn file
          withdrawn=$(grep 'withdrawn_' hgnc_index.html | awk -F '">|</a' '{print $2}' | head -n 1)
          date_new=$(echo "$complete" | awk -F '_' '{print $4}' | awk -F '.' '{print $1}')
          less hgnc_index.html
          grep -oP '(?<=href=")([^"]+(complete|withdrawn)_\d{4}-\d{2}-\d{2}\.txt)(?=")' hgnc_index.html | sort | tail -n 1


