name: Check and test HGNC updates

on:
  workflow_dispatch:
  pull_request: # tests whether it is working on PR
     paths:
     - '.github/workflows/hgnc.yml'
  schedule:
    - cron: "0 0 1,15 * *"  # Run the workflow on the 1st and 15th day of each month
permissions:
  contents: write
  pages: write
  id-token: write
  issues: write


jobs:
  check_new_data:
    runs-on: ubuntu-latest
    name: Check the date of the latest data
    outputs:
      COMPLETE_NEW: ${{ steps.check_download.outputs.COMPLETE_NEW }}
      WITHDRAWN_NEW: ${{ steps.check_download.outputs.WITHDRAWN_NEW }}
      DATE_NEW: ${{ steps.check_download.outputs.DATE_NEW }}
      DATE_OLD: ${{ steps.check_download.outputs.DATE_OLD }}
    steps:
      # step 1: check the release date for the latest HGNC files
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check for new hgnc files
        id: check_download
        run: |
          ##Extract the date from the hgnc config file 
          date_old=$(grep -E '^date=' datasources/hgnc/config | cut -d'=' -f2)
          echo 'Accessing the hgnc data'
          wget https://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/archive/quarterly/tsv/ -O hgnc_index.html
          # Extracting the latest complete file
          complete=$(grep -o 'hgnc_complete_set_[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\.txt' hgnc_index.html | tail -n 1)
          # Extracting the latest withdrawn file
          withdrawn=$(grep -o 'withdrawn_[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\.txt' hgnc_index.html | tail -n 1)
          date_new=$(echo "$complete" | awk -F '_' '{print $4}' | sed 's/\.txt//')

          #Store dates to output
          echo "DATE_OLD=$date_old" >> $GITHUB_OUTPUT
          echo "DATE_NEW=$date_new" >> $GITHUB_OUTPUT
          echo "COMPLETE_NEW=$complete" >> $GITHUB_OUTPUT
          echo "WITHDRAWN_NEW=$withdrawn" >> $GITHUB_OUTPUT

          echo "Date of latest release: $date_new", "Date of release of the current version: $date_old"
          
          
  test_new_data_processing:
    name: Processing new data and check updates
    needs: check_new_data
    env:
      DATE_OLD: ${{ needs.check_new_data.outputs.DATE_OLD }}
      DATE_NEW: ${{ needs.check_new_data.outputs.DATE_NEW }}
      COMPLETE_NEW: ${{ needs.check_new_data.outputs.COMPLETE_NEW }}
      WITHDRAWN_NEW: ${{ needs.check_new_data.outputs.WITHDRAWN_NEW }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # step 2: download the recent data 
      - name: Download the recent data
        run: |
          ##Store outputs from previous job in environment variables
          echo "$DATE_NEW=$DATE_NEW" >> $GITHUB_ENV
          echo "$COMPLETE_NEW=$COMPLETE_NEW" >> $GITHUB_ENV
          echo "$WITHDRAWN_NEW=$WITHDRAWN_NEW" >> $GITHUB_ENV
          
          ##Create temp. folder to store the data in
          mkdir -p datasources/hgnc/data
          ##Download hgnc file
          wget https://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/archive/quarterly/tsv/$(WITHDRAWN_NEW)
          wget https://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/archive/quarterly/tsv/$(COMPLETE_NEW)
          ##Check file size if available
          ls 
