name: test_hmdb

on:
  workflow_dispatch:
  
jobs:
  test_chebi:
    runs-on: ubuntu-latest
    name: test
    permissions:
      contents: write
      # step 1: checkout the repository
    steps:
      - uses: actions/checkout@v3
      # step 2: check metadata for new release date
      # step 3: 
      - name: run the script
        run: |
          sudo apt-get install xml-twig-tools
          cd datasources/hmdb
          ls
          wget http://www.hmdb.ca/system/downloads/current/hmdb_metabolites.zip
          unzip hmdb_metabolites.zip
          mkdir hmdb_data
          cd hmdb_data
          mv hmdb_metabolites.xml hmbd_data/hmdb_metabolites.xml
          xml_split -v -l 1 hmdb_metabolites.xml
          rm hmdb_metabolites.xml
          cd ../
          zip -r hmdb_metabolites_split.zip hmdb_data
      - name: Commit and Push Changes
        run: |
          git add datasources/hmdb/hmdb_metabolites_split.zip
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Automated test"
          git push
          
          
          
      
      
