# Workflow for downloading and saving Wikidata secondary2primary mappings
name: wikidata

on:
  workflow_dispatch:
  ##TODO: add schedule for deployment (suggestion: once a month?)
  
jobs:
  wikidata:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # step 1: checkout the repository
    steps:
      - name: Download GitHub repo for the queries
        uses: actions/checkout@v3

      # step 2: run the SPARQL queries from the Wikidata query subfolder
      - name: Run the Queries
        run: |
          ## Download outdated IDs for chemicals
          curl -H "Accept: text/csv" --data-urlencode query@datasources/Wikidata/queries/chemicalRedirects.rq -G https://query.wikidata.org/sparql -o datasources/Wikidata/data/chemicalRedirects.csv
          ## Download all primary IDs for chemicals
          curl -H "Accept: text/csv" --data-urlencode query@datasources/Wikidata/queries/chemicalAllPrimary.rq -G https://query.wikidata.org/sparql -o datasources/Wikidata/data/chemicalAllPrimary.csv
          ## Download alias/synonyms/names for chemicals
          curl -H "Accept: text/csv" --data-urlencode query@datasources/Wikidata/queries/chemicalPrimarySynonyms.rq -G https://query.wikidata.org/sparql -o datasources/Wikidata/data/chemicalPrimarySynonyms.csv
          
          ## Download outdated IDs for genes and proteins
          curl -H "Accept: text/csv" --data-urlencode query@datasources/Wikidata/queries/geneproteinHumanRedirects.rq -G https://query.wikidata.org/sparql -o datasources/Wikidata/data/geneproteinHumanRedirects.csv
          ## Download all primary IDs for genes and proteins
          curl -H "Accept: text/csv" --data-urlencode query@datasources/Wikidata/queries/geneproteinHumanAllPrimary.rq -G https://query.wikidata.org/sparql -o datasources/Wikidata/data/geneproteinHumanAllPrimary.csv

          ##Remove Wikidata IRIs
          cd datasources/Wikidata/data
          prefix=$(Wikidata "$PWD") # To set the prefix
          for f in * 
          do
            #cp -v "$f" "${prefix}_$f" #  
            cat "$f" | sed 's/[http://www.wikidata.org/entity/]//g' > "${prefix}_$f"
          done
          
          cd ../..
      # step 3: save the data from the queries
      - name: Commit and Push Changes
        run: |
          git pull
          ls
          git lfs track "Wikidata_chemicalRedirects.csv"
          git lfs track "Wikidata_chemicalAllPrimary.csv"
          git lfs track "Wikidata_chemicalPrimarySynonyms.csv"
          git lfs track "Wikidata_geneproteinHumanRedirects.csv"
          git lfs track "Wikidata_geneproteinHumanAllPrimary.csv"
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Updating Wd data"
          git push
